### ISSUE TITLE
Ransomware

### ISSUE THREAD

**Issue by PaulMcF1987** [C0rvust/Modular-Taskbar#13]
I have been using Rainmeter for a few weeks now and have been looking for something to replace my taskbar.
Found this and thought it could be an excellent alternative.

However,
As soon as I activated this skin, Malwarebytes quarantined Rainmeter as suspected Ransomware.
I Restored the files, reactivated the skins and the same happened.

I have again restored the files and reactivated all skins with the exception of this one and malwarebytes seems quite happy with things.

Is this something that has happened before?
Are there any reasons why malwarebytes might be reporting this?

**Comment by C0rvust** [comment]
No, never happened before. Most definitely a false positive by malwarebytes. You can view the source code in the landing page. Biggest offender would probably be `WindowsMirror.exe` from the taskbar module, which is an unused feature of the `programoptions` [plugin](https://forum.rainmeter.net/viewtopic.php?t=22868) that provides a mirror view of a particular active process.

With that said, the current build is a tad buggy and primitive. I have a build that I'll push sometime soon, which hopefully will be more refined than as it is.

As a closing note, no, there's no ransomware that will steal your spotify password.
