### ISSUE TITLE
Taskbar icons fail to load

### ISSUE THREAD

**Issue by AlsoBear** [C0rvust/Modular-Taskbar#18]
Hello,

1. Some images in the taskbar module fail to load and Rainmeter gives this error:
![image](https://user-images.githubusercontent.com/61202758/190854299-4aa789ed-427d-46f9-98e1-346765646c01.png)

It has some warnings that might or might not be relevant.

The images do appear in the corresponding folder:
![image](https://user-images.githubusercontent.com/61202758/190854600-a819d8fe-ed3c-40af-b55a-6528ad77b5fe.png)

There is empty space added on the taskbar for these applications, this empty space does not trigger any hover or click effects:
![image](https://user-images.githubusercontent.com/61202758/190854523-7c16b787-aee9-4034-9ba6-1333a4413055.png)

2. The taskbar module does not fetch images for Windows applications, such as Mail, Paint, and Task Manager. No errors are given, nor are image files added to the Dependencies\Icons folder.

**Comment by C0rvust** [comment]
> Some images in the taskbar module fail to load and Rainmeter gives this error:

For me that edge is the only replicatable case here.
 - steam should return two images, `steam.png` & `steamwebehelper.png` (did for me but not for you somehow)
 - for paint, `mspaint` wasn't retrieve (did for me but not for you somehow)
 - can't check for vscode insiders
 - in the case of edge the `programoptions` plugin returns the process name of edge as `msedge` but saves the image name as `Microsoft Edge.png`. 

> There is empty space added on the taskbar for these applications, this empty space does not trigger any hover or click effects:

> The taskbar module does not fetch images for Windows applications, such as Mail, Paint, and Task Manager. No errors are given, nor are image files added to the Dependencies\Icons folder.

I'll probably make a special case for any processes that have disparity between the process names and icon images. Additionally will have a default icon for any processes that can't retrieve an icon.

> It has some warnings that might or might not be relevant.

The warnings are fine, just ignore them. They are for deactivating popups.

**Comment by AlsoBear** [comment]
Renaming the images to the names in the Rainmeter errors worked great for me.

Although it still doesn't grab Windows Mail, Settings or Task Manager, even in the logs. Does the programoptions plugin have access to those types of applications?

**Comment by C0rvust** [comment]
Alright, so I have added a default icon that the skin falls back to if it cannot fetch an image for the program, which works fine. 

However, in the case where programoptions retrieves an image but saves it under a different name, I don't think there's much that I can do - can't exactly perform image rec to associate which misnamed image belongs to which program... unless I tag the common ones before hand.

All in all I think this is good enough. Cheers.
