### ISSUE TITLE
Module positioning

### ISSUE THREAD

**Issue by AlsoBear** [C0rvust/Modular-Taskbar#19]
Hello,

1. Changing the taskbar width from 1500px doesn't change the positioning of modules at the far end of the taskbar.
1500px:
![image](https://user-images.githubusercontent.com/61202758/190854929-003ff204-de35-439b-b21a-17a75ec2c785.png)
1200px:
![image](https://user-images.githubusercontent.com/61202758/190854950-abec73d7-2ab0-4c82-b25c-c5d76be5d31e.png)
1800px:
![image](https://user-images.githubusercontent.com/61202758/190854964-f61d0a4d-5b3c-4a72-901d-b67bfe7e373a.png)

2. Disabling modules in between others doesn't change the positioning of other modules, leaving an empty space.
With Battery module:
![image](https://user-images.githubusercontent.com/61202758/190854980-30298f91-eaa3-4f92-86e3-92d2bd96d528.png)
Without Battery module:
![image](https://user-images.githubusercontent.com/61202758/190854995-4bdf0f7e-75bb-4e55-8078-e6a90af3517b.png)

**Comment by C0rvust** [comment]
> Changing the taskbar width from 1500px doesn't change the positioning of modules at the far end of the taskbar.

I stole Khanhas' code that prevented this and was in the previous version, but forgor 💀 to put back in. Will re-implement it.

> Disabling modules in between others doesn't change the positioning of other modules, leaving an empty space.

I can't really call it an issue; each module can be moved independently of other modules, so removing one module shouldn't really effect the positioning of neighboring modules. Do you think (in your example) removing the battery module should move the volume module over to the right?

**Comment by AlsoBear** [comment]
> I can't really call it an issue; each module can be moved independently of other modules, so removing one module shouldn't really effect the positioning of neighboring modules.

I thought the modules simply appeared one by one from the edges of the taskbar, instead of having a fixed position. I didn't think to check the skin settings. Then it is indeed not a bug!

**Comment by C0rvust** [comment]
Fixed. Will be included in the next version.
