### ISSUE TITLE
Taskbar program count crash

### ISSUE THREAD

**Issue by AlsoBear** [C0rvust/Modular-Taskbar#20]
When increasing the taskbar program count, Rainmeter crashes/hangs with high cpu usage (on startup as well) until I reinstall the skin.

Rainmeter's log is spamming this. Seems to be stuck in a loop.
![image](https://user-images.githubusercontent.com/61202758/190869173-abb919b3-4468-4414-b4d5-3a34b55d4f9d.png)

**Comment by C0rvust** [comment]
As part of another [issue](issue/18), this has been fixed. A line in `\Modules\Taskbar\include\Taskbar.inc` is missing, tracking the number of generated icons (`\Module.Taskbar.GennedItemCount`) inside the generated `item.inc`.

Cheers.
