### ISSUE TITLE
uwp app icon display issue

### ISSUE THREAD

**Issue by Horizon31242** [C0rvust/Modular-Taskbar#28]
hello. First of all, thank you very much for creating a great program.

Most of it worked fine, but there was one problem. General legacy programs such as Control Panel or Edge display their icons normally when run, but uwp apps such as the Settings app or Calculator app seem to have a problem with icons not being displayed on the taskbar. Could you possibly solve this problem?

**Comment by C0rvust** [comment]
This is an issue with the `ProgramOptions` plugin itself, it's not something I can fix. If it bothers you greatly you can simply place the replacement image in `@Resources/Modules/Taskbar/Include/StockIcon` and name the file the same as the respective variable `ProcessName<N>` in the log menu.
