### ISSUE TITLE
Blank Settings Window

### ISSUE THREAD

**Issue by angiioh** [C0rvust/Modular-Taskbar#29]
Hi! Not sure if I'm doing something wrong or what, but when I try to access the settings, it doesn't seem to be loading correctly. If I click the two top icons on the left, nothing happens. The only functioning thing is clicking the x and it closes the window. Any advise? Thank you!

![image](https://github.com/C0rvust/Modular-Taskbar/assets/34181045/dd80f2d0-0a97-4ea8-a9fc-60dc1b354a2f)

**Comment by C0rvust** [comment]
Your powershell installation does not meet the minimum req by powershellRm. Follow the instructions [here](/C0rvust/Modular-Taskbar#requirements) to update your powershell version.
